services:
  landing-page:
    image: nginx:alpine
    container_name: landing-page
    profiles:
      - core
    restart: unless-stopped
    volumes:
      - ./website:/usr/share/nginx/html:ro
    networks:
      default:
        aliases:
          - landing-page

