services:
  openui:
    image: ghcr.io/wandb/openui:latest
    container_name: openui
    profiles:
    - openui
    restart: unless-stopped
    expose:
    - '7878'
    env_file:
      - .env
    environment:
    - OLLAMA_HOST=http://ollama:11434
    - OPENAI_API_KEY=${OPENAI_API_KEY:-xxx}
    - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY:-}
    - GROQ_API_KEY=${GROQ_API_KEY:-}
    - OPENAI_COMPATIBLE_ENDPOINT=${OPENAI_COMPATIBLE_ENDPOINT:-}
    volumes:
    - ./data:/app/data
    - ${PROJECT_ROOT}/services/.shared-resources/shared:/workspace
    extra_hosts:
    - host.docker.internal:host-gateway
