services:
  weaviate:
    image: cr.weaviate.io/semitechnologies/weaviate:latest
    container_name: weaviate
    profiles:
    - weaviate
    restart: unless-stopped
    volumes:
    - weaviate_data:/var/lib/weaviate
    env_file:
      - .env
    environment:
      QUERY_DEFAULTS_LIMIT: 25
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'false'
      AUTHENTICATION_APIKEY_ENABLED: 'true'
      AUTHENTICATION_APIKEY_ALLOWED_KEYS: ${WEAVIATE_API_KEY}
      AUTHENTICATION_APIKEY_USERS: ${WEAVIATE_USERNAME}
      AUTHORIZATION_ENABLE_RBAC: 'true'
      AUTHORIZATION_RBAC_ROOT_USERS: ${WEAVIATE_USERNAME}
      PERSISTENCE_DATA_PATH: /var/lib/weaviate
      ENABLE_API_BASED_MODULES: 'true'
      CLUSTER_HOSTNAME: node1
      DEFAULT_VECTORIZER_MODULE: none
    healthcheck:
      test:
      - CMD-SHELL
      - wget -q --spider http://localhost:8080/v1/.well-known/ready || exit 1
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
volumes:
  weaviate_data: {}
