services:
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    env_file:
      - .env
    profiles:
    - portainer
    restart: unless-stopped
    volumes:
    - ./data:/data
    - ${DOCKER_SOCKET_LOCATION:-/var/run/docker.sock}:/var/run/docker.sock

# volumes:
#   portainer_data: {}
