services:
  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    restart: unless-stopped
    container_name: open-webui
    profiles:
    - open-webui
    env_file:
      - .env
    environment:
    - OLLAMA_BASE_URL=http://ollama:11434
    extra_hosts:
    - host.docker.internal:host-gateway
    volumes:
    - ./data:/app/backend/data

# volumes:
#   open-webui: {}
