services:
  smtp-relay:
    image: alpine/socat
    container_name: smtp-relay
    profiles:
    - smtp-relay
    restart: unless-stopped
    command: tcp-listen:8025,fork,reuseaddr tcp-connect:mailserver:25
